{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "68135777_0ef7a27d",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 3
      },
      "lineNbr": 0,
      "author": {
        "id": 28795
      },
      "writtenOn": "2022-01-24T17:00:24Z",
      "side": 1,
      "message": "sadly a new bug was introduced and this time fod auth in apps encounters a problem. sigh",
      "revId": "85f9b8bf76bebed3ba7c659fb58eed1bf3084b2b",
      "serverId": "1ec6b3db-b2c1-4fa4-84a2-4c7efe89ba71"
    }
  ]
}